name: get_cli
version: 1.6.1
homepage: https://github.com/jonataslaw/get_cli
description: Official CLI for GetX™ framework to build Flutter and Server Applications easily
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pubspec: ^2.0.1
  meta: ^1.2.3
  recase: ^4.0.0
  cli_menu: ^0.3.0-nullsafety.0
  archive: ^3.1.2
  ansicolor: ^2.0.1
  process_run: ^0.12.1
  http: ^0.13.1
  path: ^1.7.0
  version: ^2.0.0
  intl: ^0.17.0
  cli_dialog: ^0.5.0
  dart_style: ">=2.0.1 <3.0.0"
  yaml: ^3.1.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.5.0

executables:
  get: get
  getx: get
